---
baseurl: "/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "阳明的博客"
theme: "beautifulhugo"
metaDataFormat: "yaml"
algolia:
 index: "prod_blog"
 key: "b29ea35d152a2c464151938f65716cc4"
 appID: "1JDRAS0AZR"
---
